import type { Metadata } from "next";
import { Advent_Pro, Fira_Code } from "next/font/google";
import "./globals.css";

const adventPro = Advent_Pro({
  variable: "--font-advent-pro",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${adventPro.variable} ${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
