import type { Metadata } from "next";
import { Advent_Pro, Fira_Code } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
// 1. Import the ThemeProvider you created
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "@/components/ui/modetoggle";

const adventPro = Advent_Pro({
  variable: "--font-advent-pro",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pa-Note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 2. Add suppressHydrationWarning to the <html> tag
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${adventPro.variable} ${firaCode.variable} antialiased`}
      >
        {/* 3. Wrap your existing body content with <ThemeProvider> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>{children}</AuthProvider>
          <div className="fixed bottom-4 right-4 z-50">
            <ModeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}